Repository haui-food/haui-food-client, pull requests merged in 2024-05, with the labels that each got.

#100 ✅ Build chatbot ui
  src/Layouts/DefaultLayout/DefaultLayout.js
  src/Layouts/components/Chats/Chat/Chat.js
  src/Layouts/components/Chats/Chat/Chat.module.scss
  src/Layouts/components/Chats/Chat/index.js
  src/Layouts/components/Chats/ChatBot/ChatBot.js
  src/Layouts/components/Chats/ChatBot/ChatBot.module.scss
  src/Layouts/components/Chats/ChatBot/ChatModal/ChatModal.js
  src/Layouts/components/Chats/ChatBot/ChatModal/ChatModal.module.scss
  src/Layouts/components/Chats/ChatBot/ChatModal/index.js
  src/Layouts/components/Chats/ChatBot/index.js
  src/Layouts/components/Chats/Chats.js
  src/Layouts/components/Chats/Chats.module.scss
  src/Layouts/components/Chats/index.js
Labels: create

#107 Add translation and empty order display to HistoryOrder✅
  public/locales/en/translation.json
  public/locales/vi/translation.json
  public/locales/zh/translation.json
  src/assets/images/empty-order.png
  src/assets/images/index.js
  src/components/HistoryOderItem/HistoryOderItem.js
  src/components/HistoryOrder/HistoryOder.module.scss
  src/components/HistoryOrder/HistoryOrder.js
  src/pages/Profile/Profile.js
Labels: update

#112 Integrate API to display and delete products in the shopping cart✅
  src/Layouts/components/Header/Header.js
  src/Layouts/components/Header/Header.module.scss
  src/apiService/cartService.js
  src/components/Cart/Cart.js
  src/components/Cart/Cart.module.scss
  src/components/Cart/index.js
  src/components/CartItem/CartItem.js
  src/components/CartItem/CartItem.module.scss
  src/features/cartSlice.js
Labels: create, update

#113 Update and fix some errors, integrate carts API for payment page✅
  src/Layouts/components/Header/Header.js
  src/components/Cart/Cart.js
  src/components/Cart/Cart.module.scss
  src/components/GlobalStyles/GlobalStyles.scss
  src/pages/CheckOut/CheckOut.js
  src/pages/CheckOut/CheckOut.module.scss
Labels: bug, update

#115 Fix shopping cart display error on mobile✅
  src/components/Cart/Cart.module.scss
Labels: bug

#116 Update fix shopping cart display error on mobile
  src/components/Cart/Cart.module.scss
Labels: bug, update

#117 Fix error in displaying product list on checkout page and error message✅
  src/Layouts/components/Header/Header.js
  src/pages/CheckOut/CheckOut.js
Labels: bug

#120 Update the interface and function to edit the number of products in t…
  public/locales/en/translation.json
  public/locales/vi/translation.json
  public/locales/zh/translation.json
  src/Layouts/components/Header/Header.js
  src/components/Button/Button.module.scss
  src/components/Cart/Cart.js
  src/components/Cart/Cart.module.scss
  src/components/CartItem/CartItem.js
  src/components/CartItem/CartItem.module.scss
  src/pages/CheckOut/CheckOut.js
Labels: update

#121 Fix loading display error on Checkout page✅
  src/components/Cart/Cart.js
Labels: bug

#123 Clean code part 1✅
  src/Layouts/AuthLayout/AuthLayout.js
  src/Layouts/components/Chats/ChatBot/ChatBot.js
  src/Layouts/components/Chats/ChatBot/ChatModal/ChatModal.js
  src/Layouts/components/Chats/Chats.js
  src/Layouts/components/Footer/Footer.js
  src/Layouts/components/GoToTop/GoToTop.js
  src/Layouts/components/Header/Header.js
  src/Layouts/components/QuantityDrawer/QuantityDrawer.js
  src/components/AuthTwinSetup/AuthTwinSetup.js
  src/components/Banner/Banner.js
  src/components/BreadCrumb/BreadCrumb.js
  src/components/Button/Button.js
  src/components/Cart/Cart.js
  src/components/CartItem/CartItem.js
  src/components/Help/Help.js
  src/components/ListCategorise/ListCategorise.js
  src/components/ListResult/ListResult.js
  src/components/ListSlider/ListSlider.js
  src/components/Loader/Loader.js
  src/components/NoResult/NoResult.js
  src/components/ProductCard/ProductCard.js
  src/components/RestaurantCard/RestaurantCard.js
  src/components/RestaurantHeader/RestaurantHeader.js
  src/components/RestaurantList/RestaurantList.js
  src/components/Skeleton/Skeleton.js
  src/components/TermsOfUse/TermsOfUse.js
  src/i18n.js
  src/pages/AboutHaUIFood/AboutHaUIFood.js
  src/pages/CheckOut/CheckOut.js
  src/pages/Forbidden/Forbidden.js
  src/pages/ForgotPassword/ForgotPassword.js
  src/pages/ForgotPasswordOTP/ForgotPasswordOTP.js
  src/pages/Home/Home.js
  src/pages/LoginWith2FA/LoginWith2FA.js
  src/pages/NotFound/NotFound.js
  src/pages/Profile/Profile.js
  src/pages/ResetPassword/ResetPassword.js
  src/pages/Restaurant/Restaurant.js
  src/pages/RestaurantDetail/RestaurantDetail.js
  src/pages/Restaurants/Restaurants.js
  src/pages/ServerError/ServerError.js
  src/pages/SignIn/SignIn.js
  src/pages/SignUp/SignUp.js
  src/pages/VerifyOTP/VerifyOTP.js
Labels: Clean

#124 Clean code part 2✅
  src/App.js
  src/Layouts/components/Header/Header.js
  src/Layouts/components/QuantityDrawer/QuantityDrawer.js
  src/apiService/apiUtils.js
  src/apiService/authService.js
  src/apiService/axiosInstance.js
  src/apiService/captchaService.js
  src/apiService/categoryService.js
  src/components/Cart/Cart.js
  src/components/CartItem/CartItem.js
  src/components/RestaurantHeader/RestaurantHeader.js
  src/components/RestaurantList/RestaurantList.js
  src/features/authSlice.js
  src/features/categorySlice.js
  src/features/productSlice.js
  src/features/restaurantSlice.js
  src/utils/formatCurrency.js
  src/utils/localStorage.js
Labels: Clean

#125 Update QR payment image💳
  src/assets/images/checkout/qr-payment.jpg
  src/assets/images/checkout/qr-payment.png
  src/assets/images/index.js
  src/pages/CheckOut/CheckOut.module.scss
Labels: update

#126 Update some interfaces✨
  src/components/Banner/Banner.js
  src/components/Banner/Banner.module.scss
  src/components/BreadCrumb/BreadCrumb.module.scss
  src/components/CartItem/CartItem.module.scss
  src/components/ProductCard/ProductCard.module.scss
  src/pages/Home/Home.js
  src/pages/Home/Home.module.scss
  src/pages/Profile/Profile.js
  src/pages/Profile/Profile.module.scss
  src/pages/RestaurantDetail/RestaurantDetail.js
  src/pages/RestaurantDetail/RestaurantDetail.module.scss
  src/pages/Restaurants/Restaurants.js
  src/pages/Restaurants/Restaurants.module.scss
Labels: update

#133 Fix price update error when changing quantity and updating Checkout page
  public/locales/en/translation.json
  public/locales/vi/translation.json
  public/locales/zh/translation.json
  src/components/CartItem/CartItem.js
  src/pages/CheckOut/CheckOut.js
  src/pages/CheckOut/CheckOut.module.scss
Labels: bug, update
